#!/usr/bin/python
from list import segids
import subprocess
import sys

arg1 = sys.argv[1]

print(arg1)

for e in segids:
  subprocess.call("echo segid" + e[0] +" && ./kmdcli " + e[0] + " " + arg1, shell=True)
